# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2021-2022 Eike Hein <sho@eikehein.com>

name: Android (Client)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kdeorg/android-sdk
      options: --user root

    steps:
    - name: Build for Android & archive APK
      run: |
        cp /home/user/.gitconfig /etc/gitconfig
        cd /home/user/src
        git clone https://github.com/eikehein/hyelicht.git
        cd hyelicht
        git reset --hard $GITHUB_SHA
        sh support/kde_android_docker_build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: hyelicht-arm64-v8a.apk
        path: /output/hyelicht-arm64-v8a.apk
