# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2021-2024 Eike Hein <sho@eikehein.com>

name: Linux (Onboard)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04 # Current base for KDE Neon
    container:
      image: invent-registry.kde.org/neon/docker-images/plasma:developer
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git cmake gettext
          apt-get install -y qt6-base-dev qt6-declarative-dev qt6-httpserver-dev qt6-remoteobjects-dev \
            qt6-serialport-dev qt6-shadertools-dev qt6-websockets-dev
          apt-get install -y extra-cmake-modules kf6-kconfig-dev kf6-kcoreaddons-dev kf6-ki18n-dev

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}
